apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: real_time_voting-node
  region: ap-south-1

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 3
    # will use ~/.ssh/id_rsa.pub as the default ssh key
