version: "3.8"

services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./client:/app/client
      - ./shared:/app/shared
    depends_on:
      - server
    networks:
      - app-network

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app/server
      - ./shared:/app/shared
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: "redis/redis-stack:latest"
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redisdata:
